# Generated by Django 4.1.13 on 2024-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('kind', models.CharField(choices=[('per', 'per'), ('val', 'val')], max_length=10)),
                ('amount', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('number_of_times', models.IntegerField()),
            ],
        ),
    ]
