# Generated by Django 4.1.13 on 2024-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
