# Generated by Django 4.1.13 on 2024-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0002_discount_amount_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
