# Generated by Django 4.1.13 on 2024-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stracture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecttime',
            name='status',
        ),
        migrations.AddField(
            model_name='selecttime',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selecttime',
            name='date',
            field=models.DateField(),
        ),
    ]
