# Generated by Django 4.1.13 on 2024-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stracture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecttime',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
