# Generated by Django 4.1.13 on 2024-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stracture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttime',
            name='status',
            field=models.CharField(choices=[('assignment not determined', 'تعین تکلیف نشده'), ('cancel', 'لغو شده'), ('Reserv', 'رزرو')], max_length=100),
        ),
    ]
