# Generated by Django 4.1.13 on 2024-06-27 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfCounseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.IntegerField()),
                ('survey', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('note', django_summernote.fields.SummernoteTextField()),
                ('status', models.CharField(choices=[('completing', 'completing'), ('waiting', 'waiting'), ('done', 'done'), ('cancel', 'cancel')], max_length=20)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.consultant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.auth')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visit.question')),
            ],
        ),
    ]
