# Generated by Django 4.1.13 on 2024-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_10',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_2',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_4',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_5',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_6',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_7',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_8',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_9',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f'), (7, 'g'), (8, 'h'), (9, 'j'), (10, 'k')], default=0),
            preserve_default=False,
        ),
    ]
