# Generated by Django 4.1.13 on 2024-07-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0002_visit_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='kind',
        ),
    ]
