# Generated by Django 4.1.13 on 2024-07-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='postion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
