# Generated by Django 4.1.13 on 2024-06-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='phone',
            new_name='mobile',
        ),
    ]
