# Generated by Django 4.1.13 on 2024-06-26 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auth'),
        ('Visit', '0002_alter_visit_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.auth'),
        ),
    ]
