# Generated by Django 4.1.13 on 2024-06-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_delete_authentication_alter_otp_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='auth',
            name='national_code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.BigIntegerField(max_length=800),
        ),
    ]
