# Generated by Django 4.1.13 on 2024-06-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_auth_mobile_alter_auth_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='mobile',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='national_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.auth', to_field='mobile'),
        ),
    ]
