# Generated by Django 4.1.13 on 2024-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_auth_mobile_alter_auth_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='national_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
